# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_la = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_la.setGeometry(QtCore.QRect(381, 123, 133, 24))
        self.lineEdit_la.setObjectName("lineEdit_la")
        self.lineEdit_intensity_choice = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_intensity_choice.setGeometry(QtCore.QRect(381, 158, 133, 24))
        self.lineEdit_intensity_choice.setObjectName("lineEdit_intensity_choice")
        self.label_intensity_choice = QtWidgets.QLabel(self.centralwidget)
        self.label_intensity_choice.setGeometry(QtCore.QRect(61, 158, 93, 16))
        self.label_intensity_choice.setObjectName("label_intensity_choice")
        self.label_mu = QtWidgets.QLabel(self.centralwidget)
        self.label_mu.setGeometry(QtCore.QRect(61, 84, 311, 16))
        self.label_mu.setObjectName("label_mu")
        self.label_la = QtWidgets.QLabel(self.centralwidget)
        self.label_la.setGeometry(QtCore.QRect(61, 121, 273, 16))
        self.label_la.setObjectName("label_la")
        self.lineEdit_mu = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mu.setGeometry(QtCore.QRect(381, 86, 133, 24))
        self.lineEdit_mu.setObjectName("lineEdit_mu")
        self.radioButton_alpha = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_alpha.setGeometry(QtCore.QRect(61, 195, 143, 20))
        self.radioButton_alpha.setObjectName("radioButton_alpha")
        self.pushButton_result = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_result.setGeometry(QtCore.QRect(381, 257, 93, 28))
        self.pushButton_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_result.setObjectName("pushButton_result")
        self.radioButton_beta = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_beta.setGeometry(QtCore.QRect(61, 228, 122, 20))
        self.radioButton_beta.setObjectName("radioButton_beta")
        self.label_kappa = QtWidgets.QLabel(self.centralwidget)
        self.label_kappa.setGeometry(QtCore.QRect(61, 51, 128, 16))
        self.label_kappa.setObjectName("label_kappa")
        self.lineEdit_kappa = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kappa.setGeometry(QtCore.QRect(381, 51, 133, 24))
        self.lineEdit_kappa.setObjectName("lineEdit_kappa")
        self.lineEdit_kappa.setFocus()
        self.pushButton_graphs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_graphs.setGeometry(QtCore.QRect(580, 120, 93, 28))
        self.pushButton_graphs.setObjectName("pushButton_graphs")
        self.pushButton_show_reliable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show_reliable.setGeometry(QtCore.QRect(580, 80, 93, 28))
        self.pushButton_show_reliable.setObjectName("pushButton_show_reliable")
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_result.setGeometry(QtCore.QRect(170, 310, 491, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_result.sizePolicy().hasHeightForWidth())
        self.textEdit_result.setSizePolicy(sizePolicy)
        self.textEdit_result.setReadOnly(True)
        self.textEdit_result.setObjectName("textEdit_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu_3.addAction(self.action_3)
        self.menu_3.addAction(self.action_4)
        self.menu_4.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Программа для работы с ненадежной СМО"))
        self.label_intensity_choice.setText(_translate("MainWindow", "Интенсивность:"))
        self.label_mu.setText(_translate("MainWindow", "Интенсивность обслуживания требования прибором"))
        self.label_la.setText(_translate("MainWindow", "Интенсивность входящего потока требований"))
        self.radioButton_alpha.setText(_translate("MainWindow", "Наработки на отказ"))
        self.pushButton_result.setText(_translate("MainWindow", "Подсчет"))
        self.radioButton_beta.setText(_translate("MainWindow", "Восстановления"))
        self.label_kappa.setText(_translate("MainWindow", "Количество приборов"))
        self.pushButton_graphs.setText(_translate("MainWindow", "Графики"))
        self.pushButton_show_reliable.setText(_translate("MainWindow", "Для надежной"))
        self.menu.setTitle(_translate("MainWindow", "Тип системы"))
        self.menu_3.setTitle(_translate("MainWindow", "Графики"))
        self.menu_4.setTitle(_translate("MainWindow", "О программе"))
        self.action.setText(_translate("MainWindow", "Ненадежная"))
        self.action.setStatusTip(_translate("MainWindow", "Show actions for unreliable system"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_2.setText(_translate("MainWindow", "Надежная"))
        self.action_2.setStatusTip(_translate("MainWindow", "Show actions for reliable system"))
        self.action_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_3.setText(_translate("MainWindow", "Ненадежные"))
        self.action_3.setStatusTip(_translate("MainWindow", "Show graph for unreliable system"))
        self.action_3.setShortcut(_translate("MainWindow", "Shift+N"))
        self.action_4.setText(_translate("MainWindow", "Надежные"))
        self.action_4.setStatusTip(_translate("MainWindow", "Show graph for reliable system"))
        self.action_4.setShortcut(_translate("MainWindow", "Shift+R"))
        self.action_5.setText(_translate("MainWindow", "Инфо"))
        self.action_5.setStatusTip(_translate("MainWindow", "Show program info"))
        self.action_5.setShortcut(_translate("MainWindow", "Shift+O"))
