# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 714)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_result = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_result.setGeometry(QtCore.QRect(381, 257, 93, 28))
        self.pushButton_result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_result.setObjectName("pushButton_result")
        self.pushButton_graphs = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_graphs.setGeometry(QtCore.QRect(580, 120, 93, 28))
        self.pushButton_graphs.setObjectName("pushButton_graphs")
        self.pushButton_show_reliable = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show_reliable.setGeometry(QtCore.QRect(580, 80, 93, 28))
        self.pushButton_show_reliable.setObjectName("pushButton_show_reliable")
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_result.setGeometry(QtCore.QRect(170, 310, 491, 261))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_result.sizePolicy().hasHeightForWidth())
        self.textEdit_result.setSizePolicy(sizePolicy)
        self.textEdit_result.setReadOnly(True)
        self.textEdit_result.setObjectName("textEdit_result")
        self.lineEdit_alpha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_alpha.setGeometry(QtCore.QRect(380, 131, 137, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_alpha.sizePolicy().hasHeightForWidth())
        self.lineEdit_alpha.setSizePolicy(sizePolicy)
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.label_alpha = QtWidgets.QLabel(self.centralwidget)
        self.label_alpha.setGeometry(QtCore.QRect(61, 133, 231, 16))
        self.label_alpha.setObjectName("label_alpha")
        self.label_mu = QtWidgets.QLabel(self.centralwidget)
        self.label_mu.setGeometry(QtCore.QRect(61, 104, 321, 16))
        self.label_mu.setObjectName("label_mu")
        self.lineEdit_la = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_la.setGeometry(QtCore.QRect(380, 73, 137, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_la.sizePolicy().hasHeightForWidth())
        self.lineEdit_la.setSizePolicy(sizePolicy)
        self.lineEdit_la.setObjectName("lineEdit_la")
        self.lineEdit_mu = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_mu.setGeometry(QtCore.QRect(380, 102, 137, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_mu.sizePolicy().hasHeightForWidth())
        self.lineEdit_mu.setSizePolicy(sizePolicy)
        self.lineEdit_mu.setObjectName("lineEdit_mu")
        self.label_la = QtWidgets.QLabel(self.centralwidget)
        self.label_la.setGeometry(QtCore.QRect(61, 75, 301, 16))
        self.label_la.setObjectName("label_la")
        self.label_kappa = QtWidgets.QLabel(self.centralwidget)
        self.label_kappa.setGeometry(QtCore.QRect(61, 46, 131, 16))
        self.label_kappa.setObjectName("label_kappa")
        self.lineEdit_kappa = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_kappa.setGeometry(QtCore.QRect(380, 44, 137, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_kappa.sizePolicy().hasHeightForWidth())
        self.lineEdit_kappa.setSizePolicy(sizePolicy)
        self.lineEdit_kappa.setTabletTracking(False)
        self.lineEdit_kappa.setCursorPosition(0)
        self.lineEdit_kappa.setClearButtonEnabled(False)
        self.lineEdit_kappa.setObjectName("lineEdit_kappa")
        self.lineEdit_beta = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_beta.setGeometry(QtCore.QRect(380, 160, 137, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_beta.sizePolicy().hasHeightForWidth())
        self.lineEdit_beta.setSizePolicy(sizePolicy)
        self.lineEdit_beta.setObjectName("lineEdit_beta")
        self.label_beta = QtWidgets.QLabel(self.centralwidget)
        self.label_beta.setGeometry(QtCore.QRect(61, 162, 201, 16))
        self.label_beta.setObjectName("label_beta")
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(371, 606, 93, 28))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(271, 606, 93, 28))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open.setGeometry(QtCore.QRect(471, 606, 93, 28))
        self.pushButton_open.setObjectName("pushButton_open")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Программа для работы с ненадежной СМО"))
        self.pushButton_result.setText(_translate("MainWindow", "Подсчет"))
        self.pushButton_graphs.setText(_translate("MainWindow", "Графики"))
        self.pushButton_show_reliable.setText(_translate("MainWindow", "Для надежной"))
        self.label_alpha.setText(_translate("MainWindow", "Интенсивность наработки на отказ"))
        self.label_mu.setText(_translate("MainWindow", "Интенсивность обслуживания требования прибором"))
        self.label_la.setText(_translate("MainWindow", "Интенсивность входящего потока требований"))
        self.label_kappa.setText(_translate("MainWindow", "Количество приборов"))
        self.label_beta.setText(_translate("MainWindow", "Интенсивность восстановления"))
        self.pushButton_save.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_clear.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_open.setText(_translate("MainWindow", "Открыть"))
        self.action.setText(_translate("MainWindow", "Ненадежная"))
        self.action.setStatusTip(_translate("MainWindow", "Show actions for unreliable system"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_2.setText(_translate("MainWindow", "Надежная"))
        self.action_2.setStatusTip(_translate("MainWindow", "Show actions for reliable system"))
        self.action_2.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.action_3.setText(_translate("MainWindow", "Ненадежные"))
        self.action_3.setStatusTip(_translate("MainWindow", "Show graph for unreliable system"))
        self.action_3.setShortcut(_translate("MainWindow", "Shift+N"))
        self.action_4.setText(_translate("MainWindow", "Надежные"))
        self.action_4.setStatusTip(_translate("MainWindow", "Show graph for reliable system"))
        self.action_4.setShortcut(_translate("MainWindow", "Shift+R"))
        self.action_5.setText(_translate("MainWindow", "Инфо"))
        self.action_5.setStatusTip(_translate("MainWindow", "Show program info"))
        self.action_5.setShortcut(_translate("MainWindow", "Shift+O"))
